"""JavaScript Puppeteer exporter for OctoMaster Pro."""

from typing import Dict, Any
from loguru import logger


class JavaScriptPuppeteerExporter:
    """Export workflows to JavaScript Puppeteer code."""

    def export(self, workflow: Dict[str, Any], **options) -> str:
        """Export workflow to JavaScript code."""
        lines = [
            "// Generated by OctoMaster Pro",
            "// Puppeteer automation script",
            "",
            "const puppeteer = require('puppeteer');",
            "",
            "(async () => {",
            f"  const browser = await puppeteer.launch({{ headless: {str(options.get('headless', False)).lower()} }});",
            "  const page = await browser.newPage();",
            "",
        ]

        for node in workflow.get("nodes", []):
            code = self._generate_node_code(node)
            if code:
                lines.append(f"  {code}")

        lines.extend(["", "  await browser.close();", "})();"])
        return "\n".join(lines)

    def _generate_node_code(self, node: Dict[str, Any]) -> str:
        """Generate JavaScript code for node."""
        node_type = node.get("type", "")
        params = node.get("params", {})

        if node_type == "OpenURL":
            return f"await page.goto('{params.get('url', '')}');"
        elif node_type == "Click":
            return f"await page.click('{params.get('selector', '')}');"
        elif node_type == "TypeText":
            return f"await page.type('{params.get('selector', '')}', '{params.get('text', '')}');"
        elif node_type == "Wait":
            return f"await page.waitForTimeout({int(params.get('seconds', 1)) * 1000});"
        elif node_type == "WaitForElement":
            return f"await page.waitForSelector('{params.get('selector', '')}');"
        elif node_type == "Screenshot":
            return f"await page.screenshot({{ path: '{params.get('filename', 'screenshot.png')}' }});"
        elif node_type == "ExtractText":
            selector = params.get('selector', '')
            return f"const text = await page.$eval('{selector}', el => el.textContent);\nconsole.log(text);"
        else:
            return f"// TODO: {node_type}"

    def get_format_name(self) -> str:
        return "JavaScript (Puppeteer)"

    def get_file_extension(self) -> str:
        return ".js"
