"""
Python Playwright exporter for OctoMaster Pro.

Export workflows to Python code using Playwright.
"""

from typing import Dict, Any, List
from loguru import logger


class PythonPlaywrightExporter:
    """Export workflows to Python Playwright code."""

    def __init__(self):
        """Initialize exporter."""
        logger.info("PythonPlaywrightExporter initialized")

    def export(self, workflow: Dict[str, Any], **options) -> str:
        """Export workflow to Python code.

        Args:
            workflow: Workflow data
            **options: Export options

        Returns:
            Python code as string
        """
        lines = []

        # Header comment
        lines.append("# Generated by OctoMaster Pro")
        lines.append("# Playwright automation script")
        lines.append("")

        # Imports
        lines.append("import asyncio")
        lines.append("from playwright.async_api import async_playwright, Page")
        lines.append("import time")
        lines.append("")

        # Main function
        async_mode = options.get("async", True)

        if async_mode:
            lines.append("async def main():")
            lines.append("    async with async_playwright() as p:")
        else:
            lines.append("from playwright.sync_api import sync_playwright")
            lines.append("")
            lines.append("def main():")
            lines.append("    with sync_playwright() as p:")

        # Browser launch
        headless = options.get("headless", False)
        lines.append(f"        browser = p.chromium.launch(headless={headless})")
        lines.append("        page = browser.new_page()")
        lines.append("")

        # Generate code for nodes
        nodes = workflow.get("nodes", [])

        for node in nodes:
            code = self._generate_node_code(node, async_mode)
            if code:
                for line in code.split("\n"):
                    if line:
                        lines.append(f"        {line}")

        # Cleanup
        lines.append("")
        lines.append("        browser.close()")
        lines.append("")

        # Entry point
        lines.append("if __name__ == '__main__':")
        if async_mode:
            lines.append("    asyncio.run(main())")
        else:
            lines.append("    main()")

        return "\n".join(lines)

    def _generate_node_code(self, node: Dict[str, Any], async_mode: bool = True) -> str:
        """Generate Python code for single node.

        Args:
            node: Node data
            async_mode: Use async/await

        Returns:
            Generated code
        """
        node_type = node.get("type", "")
        params = node.get("params", {})

        await_prefix = "await " if async_mode else ""

        if node_type == "OpenURL":
            url = params.get("url", "")
            return f"{await_prefix}page.goto('{url}')"

        elif node_type == "Click":
            selector = params.get("selector", "")
            return f"{await_prefix}page.click('{selector}')"

        elif node_type == "TypeText" or node_type == "Fill":
            selector = params.get("selector", "")
            text = params.get("text", "")
            return f"{await_prefix}page.fill('{selector}', '{text}')"

        elif node_type == "Wait":
            seconds = params.get("seconds", 1)
            return f"time.sleep({seconds})"

        elif node_type == "WaitForElement":
            selector = params.get("selector", "")
            timeout = params.get("timeout", 30000)
            return f"{await_prefix}page.wait_for_selector('{selector}', timeout={timeout})"

        elif node_type == "WaitForNavigation":
            return f"{await_prefix}page.wait_for_load_state()"

        elif node_type == "ExtractText":
            selector = params.get("selector", "")
            variable = params.get("variable", "text")
            return f"{variable} = {await_prefix}page.inner_text('{selector}')\nprint(f'{variable}: {{{variable}}}')"

        elif node_type == "ExtractAttribute":
            selector = params.get("selector", "")
            attribute = params.get("attribute", "href")
            variable = params.get("variable", "value")
            return f"{variable} = {await_prefix}page.get_attribute('{selector}', '{attribute}')\nprint(f'{variable}: {{{variable}}}')"

        elif node_type == "ExtractMultiple":
            container = params.get("container_selector", "")
            fields = params.get("fields", {})

            code_lines = [
                f"elements = {await_prefix}page.query_selector_all('{container}')",
                "data = []",
                "for element in elements:",
            ]

            for field_name, field_selector in fields.items():
                code_lines.append(
                    f"    {field_name} = {await_prefix}element.query_selector('{field_selector}')"
                )
                code_lines.append(
                    f"    {field_name}_text = {await_prefix}{field_name}.inner_text() if {field_name} else ''"
                )

            code_lines.append(
                f"    data.append({{{', '.join([f\"'{k}': {k}_text\" for k in fields.keys()])}}})"
            )
            code_lines.append("print(f'Extracted {{len(data)}} items')")

            return "\n".join(code_lines)

        elif node_type == "Screenshot":
            filename = params.get("filename", "screenshot.png")
            return f"{await_prefix}page.screenshot(path='{filename}')"

        elif node_type == "Scroll":
            direction = params.get("direction", "down")
            amount = params.get("amount", 1000)
            if direction == "down":
                return f"{await_prefix}page.evaluate('window.scrollBy(0, {amount})')"
            else:
                return f"{await_prefix}page.evaluate('window.scrollBy(0, -{amount})')"

        elif node_type == "CheckElement":
            selector = params.get("selector", "")
            should_exist = params.get("should_exist", True)
            if should_exist:
                return f"assert {await_prefix}page.query_selector('{selector}') is not None"
            else:
                return f"assert {await_prefix}page.query_selector('{selector}') is None"

        elif node_type == "UploadFile":
            selector = params.get("selector", "input[type='file']")
            file_path = params.get("file_path", "")
            return f"{await_prefix}page.set_input_files('{selector}', '{file_path}')"

        elif node_type == "Select":
            selector = params.get("selector", "")
            value = params.get("value", "")
            return f"{await_prefix}page.select_option('{selector}', '{value}')"

        elif node_type == "Loop":
            iterations = params.get("iterations", 1)
            return f"for i in range({iterations}):\n    # Loop body here\n    pass"

        elif node_type == "If":
            condition = params.get("condition", "True")
            return f"if {condition}:\n    # If body\n    pass"

        else:
            return f"# TODO: {node_type}"

    def get_format_name(self) -> str:
        """Get exporter format name.

        Returns:
            Format name
        """
        return "Python (Playwright)"

    def get_file_extension(self) -> str:
        """Get file extension.

        Returns:
            File extension
        """
        return ".py"
