"""Selenium exporter for OctoMaster Pro."""

from typing import Dict, Any
from loguru import logger


class SeleniumExporter:
    """Export workflows to Selenium Python code."""

    def export(self, workflow: Dict[str, Any], **options) -> str:
        """Export workflow to Selenium code."""
        lines = [
            "# Generated by OctoMaster Pro",
            "# Selenium automation script",
            "",
            "from selenium import webdriver",
            "from selenium.webdriver.common.by import By",
            "from selenium.webdriver.support.ui import WebDriverWait",
            "from selenium.webdriver.support import expected_conditions as EC",
            "import time",
            "",
            "def main():",
            "    driver = webdriver.Chrome()",
            "    wait = WebDriverWait(driver, 10)",
            "",
        ]

        for node in workflow.get("nodes", []):
            code = self._generate_node_code(node)
            if code:
                for line in code.split("\n"):
                    lines.append(f"    {line}")

        lines.extend(["", "    driver.quit()", "", "if __name__ == '__main__':", "    main()"])
        return "\n".join(lines)

    def _generate_node_code(self, node: Dict[str, Any]) -> str:
        """Generate Selenium code for node."""
        node_type = node.get("type", "")
        params = node.get("params", {})

        if node_type == "OpenURL":
            return f"driver.get('{params.get('url', '')}')"
        elif node_type == "Click":
            selector = params.get('selector', '')
            return f"element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '{selector}')))\nelement.click()"
        elif node_type == "TypeText":
            selector = params.get('selector', '')
            text = params.get('text', '')
            return f"element = driver.find_element(By.CSS_SELECTOR, '{selector}')\nelement.send_keys('{text}')"
        elif node_type == "Wait":
            return f"time.sleep({params.get('seconds', 1)})"
        elif node_type == "WaitForElement":
            selector = params.get('selector', '')
            return f"wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '{selector}')))"
        elif node_type == "Screenshot":
            return f"driver.save_screenshot('{params.get('filename', 'screenshot.png')}')"
        elif node_type == "ExtractText":
            selector = params.get('selector', '')
            return f"element = driver.find_element(By.CSS_SELECTOR, '{selector}')\ntext = element.text\nprint(text)"
        else:
            return f"# TODO: {node_type}"

    def get_format_name(self) -> str:
        return "Python (Selenium)"

    def get_file_extension(self) -> str:
        return ".py"
